### ISSUE TITLE
Exclude some forms

### ISSUE THREAD

**Issue by CarlosYohn** [VFPX/IntelliSenseX#21]
Hi,

It's possible to add a few exceptions for autocomplete procedure, based on form names or form classes?
We use I.E., a form to find text in our projects and do not want to get on key label working there.
TIA
Regards,

**Comment by Jimrnelson** [comment]
Can you provide any concrete examples?

It’s not clear to me what you want to exclude.  

Are you suggesting that there are circumstances where you want IntelliSenseX disabled, or something else?

**Comment by CarlosYohn** [comment]
Hi,
Yes. I want to disable it when running some forms or some classes of forms.


CYZ
Fuera de la Oficina
________________________________
De: Jimrnelson ***@***.***>
Enviado: Thursday, June 22, 2023 6:00:12 PM
Para: VFPX/IntelliSenseX ***@***.***>
Cc: Carlos Yohn Zubiría ***@***.***>; Author ***@***.***>
Asunto: Re: [VFPX/IntelliSenseX] Exclude some forms (Issue #21)


Can you provide any concrete examples?

It’s not clear to me what you want to exclude.

Are you suggesting that there are circumstances where you want IntelliSenseX disabled, or something else?

**Comment by Jimrnelson** [comment]
@CarlosYohn 

Carlos --

There's some good news here, as much of the work to handle this has already been done.  

And you (with some help from me) can complete it.

If you're up to the task (which is merely modifying the Timer method in an existing object), I'd be glad to provide direction.

**Comment by CarlosYohn** [comment]
Hi,

I'm sorry but don't have enough time for more projects. Just want to know if there already were a solution for this.
Many thanks anyway.


Saludos.

Carlos Yohn Zubiría - ***@***.*** <https://www.agpsoftware.com/>  - 94 480 23 45

De: Jimrnelson ***@***.***>
Enviado el: jueves, 22 de junio de 2023 20:51
Para: VFPX/IntelliSenseX ***@***.***>
CC: Carlos Yohn Zubiría ***@***.***>; Mention ***@***.***>
Asunto: Re: [VFPX/IntelliSenseX] Exclude some forms (Issue #21)


@CarlosYohn<https://github.com/CarlosYohn>

Carlos --

There's some good news here, as much of the work to handle this has already been done.

And you (with some help from me) can complete it.

If you're up to the task (which is merely modifying the Timer method in an existing object), I'd be glad to provide direction.

-

**Comment by Jimrnelson** [comment]
Carlos --

I certainly understand not having the time.  We all understand that.

This seemed like a simple enough problem for me to solve for you, so here's my take on it, which required only a few small modifications to a PRG.

[1]  Copy the text of the PRG that I've pasted in at the end of this message

[2]  In the command window,  

`Modify Command _screen.cThorFolder + "\Tools\My Tools\THOR_PROC_INTELLISENSEXTIMER.PRG"`

[3]  Paste the copied text in to the PRG and save it.

You'll then be using a private copy of the timer object that determines whether IntellisenseX is active or not.

**How to use this to achieve your goal**

You will notice that the first line of the new PRG is a defined constant.  If the form or class you are editing has a property by that name and its value is .T. then IntellisenseX will be turned off while editing any methods from that form or class.

(BTW, feel free to rename that defined constant to be anything that works for you.)

Afterthought -- it's actually taken more time to type this message than it took to write the code.




***************************************************************************************************
#Define ccDisablePropertyName	'lDisableIntellisenseXTimer'

#Define ccPropertyName  'oIntellisenseXTimer'
#Define ccClassName		'IntellisenseXTimer'


Lparameters tcAction

Local lcAction
lcAction = Proper(Evl(tcAction, 'Start'))

Do Case
	Case lcAction = 'Start'
		StopTimer()
		StartTimer()
	Case lcAction = 'Stop'
		StopTimer()
	Otherwise
		Return Execscript(_Screen.Cthordispatcher, 'Result=', ToggleTimer())
Endcase

Return

* ==========================================
Procedure StartTimer
	_Screen.AddProperty(ccPropertyName, Newobject(ccClassName))
Endproc

* ==========================================
Procedure StopTimer
	_Screen.AddProperty(ccPropertyName, Null)
Endproc

* ==========================================
Procedure ToggleTimer
	Local lcPropertyName
	lcPropertyName = ccPropertyName
	If Type([_Screen.] + lcPropertyName) = 'O' And Vartype(_Screen.&lcPropertyName) = 'O'
		StopTimer()
		Return .F.
	Else
		StartTimer()
		Return .T.
	Endif
Endproc


* ==========================================
* ==========================================
Define Class ccClassName As Custom

	cISXPRG = ''
	Procedure Init
		Local lcPRG
		lcPRG		 = Execscript(_Screen.Cthordispatcher, 'Full Path=Thor_Proc_ISX')
		This.cISXPRG = lcPRG
		This.Newobject('Timer', 'ISXTimer')
	Endproc

Enddefine

Define Class ISXTimer As Timer

	Interval = 1000
	Enabled	 = .T.

	* ==========================================
	Procedure Timer
		Local lcOnKeyDot, lcPRG, llCodeWindow

		llCodeWindow = This.GetWindowType() >= 0
		lcOnKeyDot	 = On('Key', '.')

		Do Case
			Case _Screen.lThorDebuggerOpen and Wexist('Debugger')
				StopTimer()
			
			Case This.GetWindowType() = 10 and This.CheckIfFormDisabled()
				This.StopOnKeyDot()
			
			Case llCodeWindow =(Not Empty(lcOnKeyDot))

			Case llCodeWindow
				This.StartOnKeyDot()
			Otherwise
				This.StopOnKeyDot()
		Endcase

	Endproc

	* ==========================================
	Procedure CheckIfFormDisabled
		Local loTopOfForm
	
		If Type('_oPEMEditor.oUtils') # 'O'
			Execscript (_Screen.cThorDispatcher, 'PEMEditor_StartIDETools')
		EndIf
		
		loTopOfForm = _oPEMEditor.oUtils.FindTopMostParent ()
		Return Pemstatus(m.loTopOfForm, ccDisablePropertyName, 5) And Getpem(m.loTopOfForm, ccDisablePropertyName)
	
	Endproc
	

	* ==========================================
	* ==========================================
	Procedure Destroy
		This.StopOnKeyDot()
	Endproc

	* ==========================================
	Procedure StartOnKeyDot
		Local lcPRG
		lcPRG = This.Parent.cISXPRG
		On Key Label . Do [&lcPRG] With 'VAR,OBJ,TABLE,THOR', '.'
	Endproc

	* ==========================================
	Procedure StopOnKeyDot
		On Key Label .
	Endproc

	* ==========================================
	Procedure GetWindowType
		Local laEnv[25], llResult, lnHandle, lnResult

		If Not 'FOXTOOLS.FLL' $ Upper(Set('Library'))
			Set Library To(Home() + 'FoxTools.Fll') Additive
		Endif
		lnHandle = _WonTop()

		Try
			llResult = _EdGetEnv(lnHandle, @laEnv)
		Catch
			llResult = -1
		Endtry

		If llResult > 0
			Return laEnv[25]
		Else
			Return - 1
		Endif

	Endproc

Enddefine

**Comment by Jimrnelson** [comment]
@CarlosYohn 

Carlos --

I certainly understand not having the time. We all understand that.

This seemed like a simple enough problem for me to solve for you, so here's my take on it, which required only a few small modifications to a PRG.

[1] Copy the text of the PRG that I've pasted in at the end of this message

[2] In the command window,

`Modify Command _screen.cThorFolder + "\Tools\My Tools\THOR_PROC_INTELLISENSEXTIMER.PRG"`

[3] Paste the copied text in to the PRG and save it.

You'll then be using a private copy of the timer object that determines whether IntellisenseX is active or not.

**How to use this to achieve your goal**

You will notice that the first line of the new PRG is a defined constant. If the form or class you are editing has a property by that name and its value is .T. then IntellisenseX will be turned off while editing any methods from that form or class.

(BTW, feel free to rename that defined constant to be anything that works for you.)

Afterthought -- it's actually taken more time to type this message than it took to write the code.

*****
#Define ccDisablePropertyName	'lDisableIntellisenseXTimer'

#Define ccPropertyName  'oIntellisenseXTimer'
#Define ccClassName		'IntellisenseXTimer'


Lparameters tcAction

Local lcAction
lcAction = Proper(Evl(tcAction, 'Start'))

Do Case
	Case lcAction = 'Start'
		StopTimer()
		StartTimer()
	Case lcAction = 'Stop'
		StopTimer()
	Otherwise
		Return Execscript(_Screen.Cthordispatcher, 'Result=', ToggleTimer())
Endcase

Return

* ==========================================
Procedure StartTimer
	_Screen.AddProperty(ccPropertyName, Newobject(ccClassName))
Endproc

* ==========================================
Procedure StopTimer
	_Screen.AddProperty(ccPropertyName, Null)
Endproc

* ==========================================
Procedure ToggleTimer
	Local lcPropertyName
	lcPropertyName = ccPropertyName
	If Type([_Screen.] + lcPropertyName) = 'O' And Vartype(_Screen.&lcPropertyName) = 'O'
		StopTimer()
		Return .F.
	Else
		StartTimer()
		Return .T.
	Endif
Endproc


* ==========================================
* ==========================================
Define Class ccClassName As Custom

	cISXPRG = ''
	Procedure Init
		Local lcPRG
		lcPRG		 = Execscript(_Screen.Cthordispatcher, 'Full Path=Thor_Proc_ISX')
		This.cISXPRG = lcPRG
		This.Newobject('Timer', 'ISXTimer')
	Endproc

Enddefine

Define Class ISXTimer As Timer

	Interval = 1000
	Enabled	 = .T.

	* ==========================================
	Procedure Timer
		Local lcOnKeyDot, lcPRG, llCodeWindow

		llCodeWindow = This.GetWindowType() >= 0
		lcOnKeyDot	 = On('Key', '.')

		Do Case
			Case _Screen.lThorDebuggerOpen and Wexist('Debugger')
				StopTimer()
			
			Case This.GetWindowType() = 10 and This.CheckIfFormDisabled()
				This.StopOnKeyDot()
			
			Case llCodeWindow =(Not Empty(lcOnKeyDot))

			Case llCodeWindow
				This.StartOnKeyDot()
			Otherwise
				This.StopOnKeyDot()
		Endcase

	Endproc

	* ==========================================
	Procedure CheckIfFormDisabled
		Local loTopOfForm
	
		If Type('_oPEMEditor.oUtils') # 'O'
			Execscript (_Screen.cThorDispatcher, 'PEMEditor_StartIDETools')
		EndIf
		
		loTopOfForm = _oPEMEditor.oUtils.FindTopMostParent ()
		Return Pemstatus(m.loTopOfForm, ccDisablePropertyName, 5) And Getpem(m.loTopOfForm, ccDisablePropertyName)
	
	Endproc
	

	* ==========================================
	* ==========================================
	Procedure Destroy
		This.StopOnKeyDot()
	Endproc

	* ==========================================
	Procedure StartOnKeyDot
		Local lcPRG
		lcPRG = This.Parent.cISXPRG
		On Key Label . Do [&lcPRG] With 'VAR,OBJ,TABLE,THOR', '.'
	Endproc

	* ==========================================
	Procedure StopOnKeyDot
		On Key Label .
	Endproc

	* ==========================================
	Procedure GetWindowType
		Local laEnv[25], llResult, lnHandle, lnResult

		If Not 'FOXTOOLS.FLL' $ Upper(Set('Library'))
			Set Library To(Home() + 'FoxTools.Fll') Additive
		Endif
		lnHandle = _WonTop()

		Try
			llResult = _EdGetEnv(lnHandle, @laEnv)
		Catch
			llResult = -1
		Endtry

		If llResult > 0
			Return laEnv[25]
		Else
			Return - 1
		Endif

	Endproc

Enddefine

**Comment by CarlosYohn** [comment]
Many thanks, Jim.
I’ll test it.
Regards

CYZ
Fuera de la Oficina
________________________________
De: Jimrnelson ***@***.***>
Enviado: Saturday, June 24, 2023 1:56:24 PM
Para: VFPX/IntelliSenseX ***@***.***>
Cc: Carlos Yohn Zubiría ***@***.***>; Mention ***@***.***>
Asunto: Re: [VFPX/IntelliSenseX] Exclude some forms (Issue #21)


Carlos --

I certainly understand not having the time. We all understand that.

This seemed like a simple enough problem for me to solve for you, so here's my take on it, which required only a few small modifications to a PRG.

[1] Copy the text of the PRG that I've pasted in at the end of this message

[2] In the command window,

Modify Command _screen.cThorFolder + "\Tools\My Tools\THOR_PROC_INTELLISENSEXTIMER.PRG"

[3] Paste the copied text in to the PRG and save it.

You'll then be using a private copy of the timer object that determines whether IntellisenseX is active or not.

How to use this to achieve your goal

You will notice that the first line of the new PRG is a defined constant. If the form or class you are editing has a property by that name and its value is .T. then IntellisenseX will be turned off while editing any methods from that form or class.

(BTW, feel free to rename that defined constant to be anything that works for you.)

Afterthought -- it's actually taken more time to type this message than it took to write the code.

________________________________

#Define ccDisablePropertyName 'lDisableIntellisenseXTimer'

#Define ccPropertyName 'oIntellisenseXTimer'
#Define ccClassName 'IntellisenseXTimer'

Lparameters tcAction

Local lcAction
lcAction = Proper(Evl(tcAction, 'Start'))

Do Case
Case lcAction = 'Start'
StopTimer()
StartTimer()
Case lcAction = 'Stop'
StopTimer()
Otherwise
Return Execscript(_Screen.Cthordispatcher, 'Result=', ToggleTimer())
Endcase

Return

  *   ==========================================
Procedure StartTimer
_Screen.AddProperty(ccPropertyName, Newobject(ccClassName))
Endproc

  *   ==========================================
Procedure StopTimer
_Screen.AddProperty(ccPropertyName, Null)
Endproc

  *   ==========================================
Procedure ToggleTimer
Local lcPropertyName
lcPropertyName = ccPropertyName
If Type([_Screen.] + lcPropertyName) = 'O' And Vartype(_Screen.&lcPropertyName) = 'O'
StopTimer()
Return .F.
Else
StartTimer()
Return .T.
Endif
Endproc

  *   ==========================================

  *   ==========================================
Define Class ccClassName As Custom

cISXPRG = ''
Procedure Init
Local lcPRG
lcPRG = Execscript(_Screen.Cthordispatcher, 'Full Path=Thor_Proc_ISX')
This.cISXPRG = lcPRG
This.Newobject('Timer', 'ISXTimer')
Endproc

Enddefine

Define Class ISXTimer As Timer

Interval = 1000
Enabled  = .T.

* ==========================================
Procedure Timer
        Local lcOnKeyDot, lcPRG, llCodeWindow

        llCodeWindow = This.GetWindowType() >= 0
        lcOnKeyDot       = On('Key', '.')

        Do Case
                Case _Screen.lThorDebuggerOpen and Wexist('Debugger')
                        StopTimer()

                Case This.GetWindowType() = 10 and This.CheckIfFormDisabled()
                        This.StopOnKeyDot()

                Case llCodeWindow =(Not Empty(lcOnKeyDot))

                Case llCodeWindow
                        This.StartOnKeyDot()
                Otherwise
                        This.StopOnKeyDot()
        Endcase

Endproc

* ==========================================
Procedure CheckIfFormDisabled
        Local loTopOfForm

        If Type('_oPEMEditor.oUtils') # 'O'
                Execscript (_Screen.cThorDispatcher, 'PEMEditor_StartIDETools')
        EndIf

        loTopOfForm = _oPEMEditor.oUtils.FindTopMostParent ()
        Return Pemstatus(m.loTopOfForm, ccDisablePropertyName, 5) And Getpem(m.loTopOfForm, ccDisablePropertyName)

Endproc


* ==========================================
* ==========================================
Procedure Destroy
        This.StopOnKeyDot()
Endproc

* ==========================================
Procedure StartOnKeyDot
        Local lcPRG
        lcPRG = This.Parent.cISXPRG
        On Key Label . Do [&lcPRG] With 'VAR,OBJ,TABLE,THOR', '.'
Endproc

* ==========================================
Procedure StopOnKeyDot
        On Key Label .
Endproc

* ==========================================
Procedure GetWindowType
        Local laEnv[25], llResult, lnHandle, lnResult

        If Not 'FOXTOOLS.FLL' $ Upper(Set('Library'))
                Set Library To(Home() + 'FoxTools.Fll') Additive
        Endif
        lnHandle = _WonTop()

        Try
                llResult = _EdGetEnv(lnHandle, @laEnv)
        Catch
                llResult = -1
        Endtry

        If llResult > 0
                Return laEnv[25]
        Else
                Return - 1
        Endif

Endproc


Enddefine

**Comment by Jimrnelson** [comment]
@CarlosYohn 

Carlos --

We have not heard back from you on this one, so I am will assume that this issue has been resolved.

If not, please feel free to re-open it or start a new issue.

/ Jim N
