### ISSUE TITLE
Missing file THOR_PROC_GetNamesFromCodeBlock.prg

### ISSUE THREAD

**Issue by ToniKoehler** [VFPX/IntelliSenseX#28]
## 📝 Provide detailed reproduction steps (if any)

1. Install Thor
2. Install IntelliSenseX
3. Try Autocomplete by Hotkey

### ✔️ Expected result

It should display the popup, or my variable should be autocomplete if it is unique.

### ❌ Actual result

Nothing happens, cause the file THOR_PROC_GetNamesFromCodeBlock.prg is missing in the project repository.

## 📷 Screenshots

![image](https://github.com/VFPX/IntelliSenseX/assets/44064940/e2fb5960-5774-4c7a-901e-f4531220fa14)

**Comment by Jimrnelson** [comment]
This file re-added in Version 1.25.01, Released 2024-03-06.
