### ISSUE TITLE
Missing file Thor_Proc_GetAllProcedureNames.prg

### ISSUE THREAD

**Issue by ToniKoehler** [VFPX/IntelliSenseX#29]
## 📝 Provide detailed reproduction steps (if any)

1. Install Thor
2. Install IntelliSenseX
3. Try Autocomplete by Hotkey

### ✔️ Expected result

It should display the popup with all procedures.

### ❌ Actual result

Nothing happens, cause the file Thor_Proc_GetAllProcedureNames.prg is missing in the project repository.

## 📷 Screenshots

![image](https://github.com/VFPX/IntelliSenseX/assets/44064940/52d8b441-8e5e-484f-8c3b-74aa285eeffb)

**Comment by ToniKoehler** [comment]
Also the file Thor_Proc_GetProceduresFromPRG.prg. It's called inside of Thor_Proc_GetAllProcedureNames.prg

**Comment by Jimrnelson** [comment]
This file re-added in Version 1.25.01, Released 2024-03-06.
