### ISSUE TITLE
Using IntellisenseX for "thisform.object." with no underlying table

### ISSUE THREAD

**Issue by kevclark64** [VFPX/IntelliSenseX#3]
The sample plug-in shows how to get fields from an object that is mapped to a table, but I have many situations in which objects are not mapped to tables (for example, property values are draw from several tables).  Using the fields_from_table template I created a getObjectMembers function which sort of works but only returns object member names and whether a member is a property or method. It doesn't return such things as method parameters, which would be nice.  I'm wondering how my current code could be modified to return method parameters, etc.  Here's my current code based on the template:

```
procedure getObjectMembers(lcObjectName as string)
	do case
		case lcObjectName="customer"
			local loCust as customer OF HOME()+"..\seton mks\kevin\winver\customer.vcx"
			loCust=CREATEOBJECT("customer")
			Local lxResult As 'Collection'
			Local laFields[1], laList[1]
			=AMEMBERS(laFields,locust,3)
			Dimension laList[1]
			Execscript(_Screen.cThorDispatcher, 'THOR_PROC_GetFieldNames', @laFields, @laList, 3)
			lxResult = Createobject('Empty')
			AddProperty(lxResult, 'aList[1]')
			Acopy(laList, lxResult.aList)
			RELEASE loCust
		OTHERWISE
	ENDCASE 
RETURN lxResult
```

**Comment by Jimrnelson** [comment]
@kevclark64 

I see that his issue from more than two years ago has not been addressed.

Is this still something you would like assistance with?

> The sample plug-in shows how to get fields from an object that is mapped to a table, but I have many situations in which objects are not mapped to tables (for example, property values are draw from several tables). Using the fields_from_table template I created a getObjectMembers function which sort of works but only returns object member names and whether a member is a property or method. It doesn't return such things as method parameters, which would be nice. I'm wondering how my current code could be modified to return method parameters, etc. Here's my current code based on the template:
> 
> ```
> procedure getObjectMembers(lcObjectName as string)
> 	do case
> 		case lcObjectName="customer"
> 			local loCust as customer OF HOME()+"..\seton mks\kevin\winver\customer.vcx"
> 			loCust=CREATEOBJECT("customer")
> 			Local lxResult As 'Collection'
> 			Local laFields[1], laList[1]
> 			=AMEMBERS(laFields,locust,3)
> 			Dimension laList[1]
> 			Execscript(_Screen.cThorDispatcher, 'THOR_PROC_GetFieldNames', @laFields, @laList, 3)
> 			lxResult = Createobject('Empty')
> 			AddProperty(lxResult, 'aList[1]')
> 			Acopy(laList, lxResult.aList)
> 			RELEASE loCust
> 		OTHERWISE
> 	ENDCASE 
> RETURN lxResult
> ```

**Comment by Jimrnelson** [comment]
@kevclark64 

We have not heard back from you on this one, so I am will assume that this issue has been resolved.

If not, please feel free to re-open it or start a new issue.
