### ISSUE TITLE
IntellisenseX goes nuts

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/IntelliSenseX#4]
I have been trying to work with IntellisenseX as it appears it would simply things for me as intended. I am having many issues. I have put together a little video attached...when I start to type within a program it inserts all kind of letters and carriage returns as it does its job. Hopefully the video will better explain what I am seeing

https://user-images.githubusercontent.com/34104227/179856236-46ff8a61-b740-4501-aceb-03f6b66f6b2b.mp4

.

**Comment by Jimrnelson** [comment]
I believe that this comment is about a different project, [IntelliSenseManager](https://github.com/VFPX/IntelliSenseManager)
