### ISSUE TITLE
My Thor can't find Thor_Proc_ISX_Utilities

### ISSUE THREAD

**Issue by DanielCarlos231** [VFPX/IntelliSenseX#5]
My Thor can't find Thor_Proc_ISX_Utilities... I have searched all the folders
I have installed Thor inside an Folder and I have a PRG that preps up my work environment, so added a "DO \MyFolder\Thor.app"  to that PRG.
The problem is that some features don't work properly, and my intellisenseX is one of them.
IF I select a function, which is declared in another PRG (from what I understood it would open up that PRG), and go to "Thor Tools->Go to->Go to Definition" the Thor APP throws an error saying that it can't find Thor_Proc_ISX_Utilities.
My intellisenseX is not activated at all, I mean the default one on VFP9 works, but the intellisenseX doesn't seem to be activated and I think tha it is because the Thor is not finding the Thor_Proc_ISX_Utilities.

**Comment by Jimrnelson** [comment]
@DanielCarlos231 

GoToDefinition takes advantage of some of the features provided in IntellisenseX.

This problem should disappear if you use "Check For Updates" in Thor to install IntellisenseX even if you have no intent of ever using IntellisenseX.

If this does not work or if you are not willing to install IntellisenseX, please include a screenshot of the debugger showing the execution stack and the code where the error occurs.

**Comment by DanielCarlos231** [comment]
Thanks for the reply, I had previously tried to "Check for Updates"  and it didn't work... But as of a recent update in Thor the issue disappeared, and I was able to try out the "IntellisenseX" and the "Go to Definition" tool.
I sincerly love what you guys are doing with Thor, I'm a bit of a fun
